import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, CircleDashed, RotateCcw, Send, Undo2 } from "lucide-react";
import { api, Content, PublicationChannel, PublicationRecord } from "../../lib/api";

const stateName:Record<string,string>={queued:"等待发布",publishing:"发布中",published:"已发布",retry_wait:"等待重试",failed:"失败",dead:"已停止",cancelled:"已取消",withdrawn:"已撤回"};
export function PublicationPanel({workspace,role,onOpenContent}:{workspace:string;role:string;onOpenContent:(id:string)=>void}){
 const[records,setRecords]=useState<PublicationRecord[]>([]),[channels,setChannels]=useState<PublicationChannel[]>([]),[contents,setContents]=useState<Content[]>([]),[selected,setSelected]=useState(""),[locale,setLocale]=useState(""),[scheduled,setScheduled]=useState(""),[status,setStatus]=useState("");const canEdit=role==="owner"||role==="editor";
 const load=useCallback(async()=>{try{const[recordResult,channelResult,contentResult]=await Promise.all([api.publicationRecords(workspace),api.publicationChannels(workspace),api.list(workspace)]);setRecords(recordResult.items);setChannels(channelResult.items);setContents(contentResult.items)}catch(error){setStatus(error instanceof Error?error.message:"发布中心加载失败")}},[workspace]);useEffect(()=>{void load()},[load]);
 const current=useMemo(()=>contents.find(item=>item.id===selected),[contents,selected]);useEffect(()=>{if(current&&!current.localizations.some(item=>item.locale===locale))setLocale(current.localizations[0]?.locale??"")},[current,locale]);
 async function schedule(){if(!selected||!locale||!scheduled)return;try{await api.schedulePublication(workspace,{content_id:selected,locale,scheduled_at:new Date(scheduled).toISOString()});setStatus("已加入发布计划");await load()}catch(error){setStatus(error instanceof Error?error.message:"定时发布失败")}}
 async function action(kind:"retry"|"withdraw",id:string){try{if(kind==="retry")await api.retryPublication(workspace,id);else if(window.confirm("确认撤回这条公开内容？"))await api.withdrawPublication(workspace,id);else return;await load()}catch(error){setStatus(error instanceof Error?error.message:"操作失败")}}
 return <section className="publication-page"><header className="page-heading"><div><span className="eyebrow">PUBLISHING</span><h1>发布中心</h1><p>统一查看渠道状态、发布计划、执行记录与失败原因。</p></div></header>
  <div className="channel-grid">{channels.map(item=><article key={item.channel}><span>{item.status==="ready"?<CheckCircle2/>:<CircleDashed/>}</span><div><strong>{item.name}</strong><p>{item.detail}</p></div><b data-state={item.status}>{item.status==="ready"?"可用":item.status==="disabled"?"已关闭":item.status==="planned"?"待接入":"未配置"}</b></article>)}</div>
  {canEdit&&<section className="schedule-card"><div><CalendarClock/><span><strong>安排定时发布</strong><small>内容语言版本需已标记为“就绪”</small></span></div><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">选择内容</option>{contents.map(item=><option key={item.id} value={item.id}>{item.localizations[0]?.current_revision?.title||"未命名内容"}</option>)}</select><select value={locale} onChange={e=>setLocale(e.target.value)} disabled={!current}><option value="">选择语言</option>{current?.localizations.map(item=><option key={item.id} value={item.locale}>{item.locale}</option>)}</select><input type="datetime-local" value={scheduled} onChange={e=>setScheduled(e.target.value)}/><button className="primary" disabled={!selected||!locale||!scheduled} onClick={()=>void schedule()}><Send size={16}/>加入计划</button></section>}
  <p className="inline-status" role="status">{status}</p><div className="publication-table"><div className="publication-table-head"><span>内容 / 渠道</span><span>状态</span><span>时间</span><span>执行</span></div>{records.length===0?<div className="publication-empty">暂无发布记录</div>:records.map(item=><article key={item.id}><button className="publication-title" onClick={()=>onOpenContent(item.content_id)}><strong>{item.title}</strong><small>{item.locale} · {item.channel}</small></button><span className={`publication-state state-${item.state}`}>{stateName[item.state]||item.state}</span><span><small>{item.scheduled_at?`计划 ${new Date(item.scheduled_at).toLocaleString("zh-CN")}`:item.published_at?`发布 ${new Date(item.published_at).toLocaleString("zh-CN")}`:new Date(item.created_at).toLocaleString("zh-CN")}</small>{item.last_error&&<em title={item.last_error}>{item.last_error}</em>}</span><span className="publication-actions">{canEdit&&["failed","dead","retry_wait","cancelled"].includes(item.state)&&<button title="重试" onClick={()=>void action("retry",item.id)}><RotateCcw size={16}/></button>}{canEdit&&["published","queued","retry_wait"].includes(item.state)&&<button title="撤回" onClick={()=>void action("withdraw",item.id)}><Undo2 size={16}/></button>}</span></article>)}</div>
 </section>
}
