import { useCallback, useEffect, useMemo, useState } from "react";
import { Sparkles } from "lucide-react";
import { api, AIRun, AISuggestion, Content, waitForTask } from "../../lib/api";
import { AIRunList } from "./AIRunList";
import { SuggestionReview } from "./SuggestionReview";
import { WorkspacePage } from "../studio/WorkspacePage";

const purposes=[{id:"summary",label:"生成摘要"},{id:"tags",label:"标签建议"},{id:"seo",label:"SEO 优化"},{id:"entities",label:"实体识别"},{id:"alt_text",label:"图片 Alt"},{id:"related",label:"相关文章"}];
export function AIAssistantPanel({workspace,role,onOpenContent}:{workspace:string;role:string;onOpenContent:(id:string)=>void}){
 const [contents,setContents]=useState<Content[]>([]),[suggestions,setSuggestions]=useState<AISuggestion[]>([]),[runs,setRuns]=useState<AIRun[]>([]),[targetID,setTargetID]=useState(""),[purpose,setPurpose]=useState("summary"),[busy,setBusy]=useState(false),[status,setStatus]=useState("");const canEdit=role==="owner"||role==="editor";
 const load=useCallback(async()=>{const [contentResult,suggestionResult,runResult]=await Promise.all([api.list(workspace),api.aiSuggestions(workspace),api.aiRuns(workspace)]);setContents(contentResult.items);setSuggestions(suggestionResult.items);setRuns(runResult.items);setTargetID(value=>value||contentResult.items[0]?.id||"")},[workspace]);useEffect(()=>{void load().catch(error=>setStatus(error instanceof Error?error.message:"AI 助手加载失败"))},[workspace]);
 const selected=useMemo(()=>contents.find(item=>item.id===targetID),[contents,targetID]);
 async function generate(){const localization=selected?.localizations[0],revision=localization?.current_revision;if(!selected||!localization||!revision)return;setBusy(true);setStatus("AI 任务已提交，正在后台生成建议…");try{const candidates=purpose==="related"?contents.filter(item=>item.id!==selected.id).map(item=>({object_id:item.id,title:item.localizations[0]?.current_revision?.title??""})):undefined;const queued=await api.aiSuggest(workspace,{target_id:selected.id,localization_id:localization.id,purpose,input:JSON.stringify({title:revision.title,summary:revision.summary,body:revision.body,metadata:revision.metadata,candidates})});await waitForTask(workspace,queued.job_id);await load();setStatus("建议已生成，请在下方审核")}catch(error){setStatus(error instanceof Error?error.message:"生成失败")}finally{setBusy(false)}}
 return <WorkspacePage className="ai-page" eyebrow="AI WORKBENCH" title="AI 助手" description="生成内容与 SEO 建议，集中审核运行结果和失败记录。"><div className="ai-workspace"><div className="ai-primary"><section className="ai-generator"><div><span className="workflow-step">01</span><Sparkles/><span><strong>生成新建议</strong><small>选择内容和任务，结果不会直接修改草稿。</small></span></div><select aria-label="选择内容" value={targetID} onChange={e=>setTargetID(e.target.value)}>{contents.map(item=><option key={item.id} value={item.id}>{item.localizations[0]?.current_revision?.title??"无标题"}</option>)}</select><select aria-label="选择 AI 任务" value={purpose} onChange={e=>setPurpose(e.target.value)}>{purposes.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><button className="primary compact" disabled={!canEdit||busy||!targetID} onClick={()=>void generate()}>{busy?"生成中…":"生成建议"}</button></section>{status&&<p className="inline-status" role="status">{status}</p>}<div className="workflow-section" data-step="02"><SuggestionReview workspace={workspace} items={suggestions} canEdit={canEdit} onReload={load} onOpenContent={onOpenContent}/></div></div><aside className="ai-secondary workflow-section" data-step="03"><AIRunList items={runs}/></aside></div></WorkspacePage>
}
