import { Check, Clipboard, LoaderCircle, X } from "lucide-react";
import { useState } from "react";
import { api, AISuggestion } from "../../lib/api";

const labels:Record<string,string>={summary:"摘要",tags:"标签",seo:"SEO 优化",entities:"实体识别",alt_text:"图片 Alt",related:"相关内容"};
export function SuggestionReview({workspace,items,canEdit,onReload,onOpenContent}:{workspace:string;items:AISuggestion[];canEdit:boolean;onReload:()=>Promise<void>;onOpenContent:(id:string)=>void}){
 const [active,setActive]=useState(""),[status,setStatus]=useState("");
 async function review(id:string,state:"accepted"|"rejected"){setActive(id);setStatus("");try{await api.reviewAISuggestion(workspace,id,state);await onReload();setStatus(state==="accepted"?"建议已应用到对应内容草稿":"建议已拒绝")}catch(error){setStatus(error instanceof Error?error.message:"建议处理失败")}finally{setActive("")}}
 return <section className="suggestion-review"><header><div><h2>建议审核</h2><p>接受后会写入对应语言草稿；实体与相关文章会写入知识关系。</p></div><span>{items.filter(item=>item.state==="pending").length} 项待审核</span></header>{status&&<p className="inline-status" role="status">{status}</p>}<div className="suggestion-list">{items.map(item=><article key={item.id} aria-busy={active===item.id}><div className="suggestion-meta"><button onClick={()=>onOpenContent(item.target_id)}>{item.target_title||item.target_id.slice(0,8)}</button><span>{labels[item.kind]??item.kind}</span><small>{item.state}</small></div><pre>{item.payload?.text??JSON.stringify(item.payload,null,2)}</pre><div className="suggestion-actions"><button className="secondary compact" onClick={()=>void navigator.clipboard.writeText(item.payload?.text??JSON.stringify(item.payload))}><Clipboard/>复制结果</button>{canEdit&&item.state==="pending"&&<><button className="secondary compact" disabled={Boolean(active)} onClick={()=>void review(item.id,"rejected")}><X/>拒绝</button><button className="primary compact" disabled={Boolean(active)} onClick={()=>void review(item.id,"accepted")}>{active===item.id?<LoaderCircle className="spin"/>:<Check/>}接受并应用</button></>}</div></article>)}{!items.length&&<div className="collection-empty"><p>还没有 AI 建议</p></div>}</div></section>
}
