import { useEffect, useMemo, useState } from "react";
import { Archive, File, Image as ImageIcon, Link2, Search } from "lucide-react";
import { api, Asset, AssetUsage } from "../../lib/api";
import { AssetUpload } from "./AssetUpload";
import { WorkspacePage } from "../studio/WorkspacePage";

function size(value:number){if(value<1024)return `${value} B`;if(value<1024*1024)return `${Math.ceil(value/1024)} KB`;return `${(value/1024/1024).toFixed(1)} MB`}
export function AssetsPanel({workspace,canEdit,onOpenContent}:{workspace:string;canEdit:boolean;onOpenContent:(id:string)=>void}){
  const [items,setItems]=useState<Asset[]>([]),[selected,setSelected]=useState<Asset>(),[usages,setUsages]=useState<AssetUsage[]>([]),[query,setQuery]=useState(""),[kind,setKind]=useState(""),[status,setStatus]=useState("正在加载资产…");
  async function load(){try{const value=await api.assets(workspace);setItems(value.items);setSelected(current=>value.items.find(item=>item.id===current?.id)??value.items[0]);setStatus("")}catch(error){setStatus(error instanceof Error?error.message:"资产加载失败")}}
  useEffect(()=>{void load()},[workspace]);
  useEffect(()=>{if(!selected){setUsages([]);return}void api.assetUsages(workspace,selected.id).then(value=>setUsages(value.items)).catch(()=>setUsages([]))},[workspace,selected?.id]);
  const filtered=useMemo(()=>items.filter(item=>(!kind||item.media_type===kind)&&(!query||item.filename.toLowerCase().includes(query.toLowerCase())||item.mime.toLowerCase().includes(query.toLowerCase()))),[items,query,kind]);
  async function archive(){if(!selected||!window.confirm(`确认归档“${selected.filename}”？`))return;try{await api.archiveAsset(workspace,selected.id);setSelected(undefined);await load()}catch(error){setStatus(error instanceof Error?error.message:"归档失败")}}
  async function replace(replacement:Asset){if(!selected)return;try{const next=await api.replaceAsset(workspace,selected.id,replacement.id);setSelected(next);await load();setStatus("资产已替换，已有引用保持不变")}catch(error){setStatus(error instanceof Error?error.message:"替换失败")}}
  return <WorkspacePage className="assets-page" eyebrow="ASSET LIBRARY" title="资产中心" description="管理原始文件、派生图片、引用关系和内容中的图片。" actions={canEdit&&<AssetUpload workspace={workspace} onUploaded={asset=>{setItems(value=>[asset,...value]);setSelected(asset)}}/>}><div className="asset-controls"><label><Search aria-hidden/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索文件名或类型…"/></label><select aria-label="资产类型" value={kind} onChange={e=>setKind(e.target.value)}><option value="">全部文件</option><option value="image">图片</option><option value="file">其他文件</option></select><span>{filtered.length} 项</span></div>{status&&<p className="inline-status" role="status">{status}</p>}<div className="asset-workspace"><div className="asset-grid">{filtered.map(item=><button key={item.id} className={selected?.id===item.id?"asset-card selected":"asset-card"} onClick={()=>setSelected(item)}>{item.media_type==="image"?<img src={`/media/${item.id}/thumbnail`} alt=""/>:<span className="asset-file"><File aria-hidden/></span>}<span><strong>{item.filename}</strong><small>{item.mime} · {size(item.size)}</small></span></button>)}{filtered.length===0&&<div className="asset-empty"><ImageIcon aria-hidden/><p>没有匹配的资产</p></div>}</div>{selected&&<aside className="asset-detail"><div className="asset-preview">{selected.media_type==="image"?<img src={`/media/${selected.id}/content-1280`} alt={selected.filename}/>:<File aria-hidden/>}</div><h2>{selected.filename}</h2><dl><div><dt>类型</dt><dd>{selected.mime}</dd></div><div><dt>大小</dt><dd>{size(selected.size)}</dd></div>{Boolean(selected.width&&selected.height)&&<div><dt>尺寸</dt><dd>{selected.width} × {selected.height}</dd></div>}<div><dt>派生图片</dt><dd>{selected.variants?.length??0} 个</dd></div><div><dt>引用</dt><dd>{selected.usage_count} 处</dd></div><div><dt>SHA-256</dt><dd title={selected.sha256}>{selected.sha256.slice(0,16)}…</dd></div></dl><section className="asset-usages"><h3>使用位置</h3>{usages.length?<ul>{usages.map(usage=><li key={usage.id}><Link2 aria-hidden/><button onClick={()=>onOpenContent(usage.owner_id)}>{usage.owner_title||usage.owner_id}<small>{usage.role==="cover"?"封面":"正文图片"}</small></button></li>)}</ul>:<p>尚未被内容引用</p>}</section>{canEdit&&<div className="asset-detail-actions"><AssetUpload workspace={workspace} label="上传替换文件" onUploaded={asset=>void replace(asset)}/><button className="secondary" disabled={selected.usage_count>0} onClick={()=>void archive()}><Archive aria-hidden/>归档未使用资产</button></div>}</aside>}</div></WorkspacePage>;
}
