import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, ExternalLink, Trash2 } from "lucide-react";
import { api, Collection, Content } from "../../lib/api";

export function CollectionDetail({workspace,value,canEdit,onReload,onOpenContent}:{workspace:string;value:Collection;canEdit:boolean;onReload:()=>Promise<void>;onOpenContent:(id:string)=>void}){
 const [contents,setContents]=useState<Content[]>([]),[sectionTitle,setSectionTitle]=useState(""),[selection,setSelection]=useState<Record<string,string>>({}),[error,setError]=useState("");
 useEffect(()=>{api.list(workspace).then(v=>setContents(v.items)).catch(()=>setContents([]))},[workspace]);
 async function action(run:()=>Promise<unknown>){setError("");try{await run();await onReload()}catch(err){setError(err instanceof Error?err.message:"操作失败，请重试")}}
 return <section className="collection-detail"><header><div><span className="eyebrow">COLLECTION</span><h2>{value.title}</h2><p>/{value.slug} · {value.visibility==="public"?"公开":value.visibility==="unlisted"?"不公开列出":"私有"}</p></div></header>
  {error&&<div className="inline-error" role="alert"><span>{error}</span><button onClick={()=>setError("")}>关闭</button></div>}
  {canEdit&&<form className="section-create" onSubmit={e=>{e.preventDefault();void action(async()=>{await api.addCollectionSection(workspace,value.id,sectionTitle);setSectionTitle("")})}}><label><span>新分区名称</span><input required value={sectionTitle} onChange={e=>setSectionTitle(e.target.value)} placeholder="例如：入门阅读"/></label><button className="secondary compact">添加分区</button></form>}
  <div className="section-list">{value.sections.length===0?<div className="collection-empty"><h3>还没有分区</h3><p>先创建分区，再把内容按阅读或展示顺序加入。</p></div>:value.sections.map((section,sectionIndex)=><article className="collection-section" key={section.id}><header><h3>{section.title}</h3>{canEdit&&<div className="order-actions"><button className="icon-button" aria-label={`上移分区 ${section.title}`} disabled={sectionIndex===0} onClick={()=>void action(()=>api.moveCollectionSection(workspace,value.id,section.id,-1))}><ArrowUp/></button><button className="icon-button" aria-label={`下移分区 ${section.title}`} disabled={sectionIndex===value.sections.length-1} onClick={()=>void action(()=>api.moveCollectionSection(workspace,value.id,section.id,1))}><ArrowDown/></button></div>}</header>
   {section.items.length===0?<p className="section-empty">此分区还没有内容。</p>:<ol>{section.items.map((item,index)=><li key={item.id}><button className="collection-content" onClick={()=>onOpenContent(item.object_id)}>{item.title||"无标题内容"}<ExternalLink aria-hidden size={15}/></button>{canEdit&&<div className="order-actions"><button className="icon-button" aria-label={`上移 ${item.title}`} disabled={index===0} onClick={()=>void action(()=>api.moveCollectionItem(workspace,item.id,-1))}><ArrowUp/></button><button className="icon-button" aria-label={`下移 ${item.title}`} disabled={index===section.items.length-1} onClick={()=>void action(()=>api.moveCollectionItem(workspace,item.id,1))}><ArrowDown/></button><button className="icon-button danger-icon" aria-label={`移除 ${item.title}`} onClick={()=>{if(window.confirm(`确认从合集移除“${item.title}”？内容本身不会被删除。`))void action(()=>api.removeCollectionItem(workspace,item.id))}}><Trash2/></button></div>}</li>)}</ol>}
   {canEdit&&<div className="add-content"><select aria-label={`选择要加入 ${section.title} 的内容`} value={selection[section.id]??""} onChange={e=>setSelection(v=>({...v,[section.id]:e.target.value}))}><option value="">选择内容…</option>{contents.filter(c=>!section.items.some(i=>i.object_id===c.id)).map(c=><option key={c.id} value={c.id}>{c.localizations[0]?.current_revision?.title||"无标题"}</option>)}</select><button className="secondary compact" disabled={!selection[section.id]} onClick={()=>void action(async()=>{await api.addCollectionItem(workspace,section.id,selection[section.id]);setSelection(v=>({...v,[section.id]:""}))})}>加入</button></div>}
  </article>)}</div>
 </section>
}
