import { useEffect, useState } from "react";
import { Check, Plus, Trash2 } from "lucide-react";
import { api, KnowledgeEntity, KnowledgeRelation } from "../../lib/api";

export function EntityDetail({workspace,entity,entities,canEdit,onReload}:{workspace:string;entity:KnowledgeEntity;entities:KnowledgeEntity[];canEdit:boolean;onReload:()=>Promise<void>}){
 const [relations,setRelations]=useState<KnowledgeRelation[]>([]),[form,setForm]=useState({type:entity.type,name:entity.canonical_name,description:entity.description}),[alias,setAlias]=useState(""),[locale,setLocale]=useState("zh-CN"),[target,setTarget]=useState(""),[predicate,setPredicate]=useState("related_to"),[status,setStatus]=useState("");
 useEffect(()=>{setForm({type:entity.type,name:entity.canonical_name,description:entity.description});setTarget(entities.find(item=>item.id!==entity.id)?.id??"");void api.knowledgeRelations(workspace,entity.id).then(v=>setRelations(v.items))},[workspace,entity.id]);
 async function action(run:()=>Promise<unknown>,message:string){try{await run();setStatus(message);await onReload();setRelations((await api.knowledgeRelations(workspace,entity.id)).items)}catch(error){setStatus(error instanceof Error?error.message:"操作失败")}}
 const name=(id:string)=>entities.find(item=>item.id===id)?.canonical_name??id.slice(0,8);
 return <section className="entity-detail"><header><div><span className="entity-kind">{entity.type}</span><h2>{entity.canonical_name}</h2></div>{canEdit&&<button className="danger-icon icon-button" aria-label="删除实体" onClick={()=>{if(window.confirm(`确认删除“${entity.canonical_name}”？相关别名和关系也会删除。`))void action(()=>api.deleteEntity(workspace,entity.id),"实体已删除")}}><Trash2/></button>}</header>
  <div className="entity-fields"><label>类型<input disabled={!canEdit} value={form.type} onChange={e=>setForm(v=>({...v,type:e.target.value}))}/></label><label>规范名称<input disabled={!canEdit} value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label className="wide">说明<textarea disabled={!canEdit} value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></label>{canEdit&&<button className="primary compact" onClick={()=>void action(()=>api.updateEntity(workspace,entity.id,{type:form.type,canonical_name:form.name,description:form.description}),"实体已保存")}>保存实体</button>}</div>
  <section className="knowledge-subsection"><h3>别名</h3><div className="alias-list">{entity.aliases?.map(item=><span key={item.id}>{item.value}<small>{item.locale}</small>{canEdit&&<button aria-label={`删除别名 ${item.value}`} onClick={()=>void action(()=>api.deleteEntityAlias(workspace,item.id),"别名已删除")}><Trash2/></button>}</span>)}{!entity.aliases?.length&&<p>暂无别名</p>}</div>{canEdit&&<div className="inline-create"><input value={alias} onChange={e=>setAlias(e.target.value)} placeholder="添加别名"/><select value={locale} onChange={e=>setLocale(e.target.value)}><option>zh-CN</option><option>en</option></select><button disabled={!alias.trim()} onClick={()=>void action(async()=>{await api.addEntityAlias(workspace,entity.id,{value:alias,locale});setAlias("")},"别名已添加")}><Plus/>添加</button></div>}</section>
  <section className="knowledge-subsection"><h3>关系</h3><div className="relation-list">{relations.map(item=><article key={item.id}><span>{name(item.source_id)} <strong>{item.predicate}</strong> {name(item.target_id)}</span><div>{!item.confirmed&&canEdit&&<button title="确认关系" onClick={()=>void action(()=>api.confirmKnowledgeRelation(workspace,item.id),"关系已确认")}><Check/></button>}{canEdit&&<button title="删除关系" onClick={()=>void action(()=>api.deleteKnowledgeRelation(workspace,item.id),"关系已删除")}><Trash2/></button>}</div></article>)}{!relations.length&&<p>暂无关系</p>}</div>{canEdit&&<div className="inline-create relation-create"><select value={predicate} onChange={e=>setPredicate(e.target.value)}><option value="related_to">相关</option><option value="part_of">属于</option><option value="created_by">创建者</option><option value="located_in">位于</option><option value="uses">使用</option></select><select value={target} onChange={e=>setTarget(e.target.value)}>{entities.filter(item=>item.id!==entity.id).map(item=><option key={item.id} value={item.id}>{item.canonical_name}</option>)}</select><button disabled={!target} onClick={()=>void action(()=>api.createKnowledgeRelation(workspace,{source_id:entity.id,target_id:target,predicate,confirmed:true}),"关系已添加")}><Plus/>关联</button></div>}</section>
  {status&&<p className="inline-status" role="status">{status}</p>}
 </section>
}
