import { useCallback, useEffect, useState } from "react";
import { Check, Network, Plus, ScanSearch } from "lucide-react";
import { api, KnowledgeEntity, KnowledgeMention } from "../../lib/api";
import { EntityDetail } from "./EntityDetail";
import { WorkspacePage } from "../studio/WorkspacePage";

export function KnowledgePanel({workspace,role,onOpenContent}:{workspace:string;role:string;onOpenContent:(id:string)=>void}){
 const [items,setItems]=useState<KnowledgeEntity[]>([]),[selectedID,setSelectedID]=useState(""),[mentions,setMentions]=useState<KnowledgeMention[]>([]),[query,setQuery]=useState(""),[creating,setCreating]=useState(false),[form,setForm]=useState({type:"topic",canonical_name:"",description:""}),[status,setStatus]=useState("");const canEdit=role==="owner"||role==="editor";
 const load=useCallback(async()=>{const [entitiesResult,mentionsResult]=await Promise.all([api.entities(workspace,query),api.knowledgeMentions(workspace)]);setItems(entitiesResult.items);setMentions(mentionsResult.items);setSelectedID(current=>entitiesResult.items.some(item=>item.id===current)?current:entitiesResult.items[0]?.id??"")},[workspace,query]);
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(error=>setStatus(error instanceof Error?error.message:"知识库加载失败")),query?250:0);return()=>clearTimeout(timer)},[workspace,query]);
 const selected=items.find(item=>item.id===selectedID);
 async function create(){try{const value=await api.createEntity(workspace,form);setCreating(false);setForm({type:"topic",canonical_name:"",description:""});await load();setSelectedID(value.id)}catch(error){setStatus(error instanceof Error?error.message:"实体创建失败")}}
 async function extract(){try{setStatus("正在扫描已发布版本…");const result=await api.extractKnowledgeMentions(workspace);setMentions(result.items);setStatus(`发现 ${result.items.length} 个待确认提及`)}catch(error){setStatus(error instanceof Error?error.message:"提及抽取失败")}}
 return <WorkspacePage className="knowledge-page" eyebrow="KNOWLEDGE GRAPH" title="知识" description="统一管理人物、品牌、地点、主题及内容之间的关系。" actions={canEdit&&<><button className="secondary compact" onClick={()=>void extract()}><ScanSearch/>抽取提及</button><button className="primary compact" onClick={()=>setCreating(true)}><Plus/>新建实体</button></>}>
  {status&&<p className="inline-status" role="status">{status}</p>}
  {creating&&<div className="knowledge-create"><input placeholder="类型，如 person、brand、topic" value={form.type} onChange={e=>setForm(v=>({...v,type:e.target.value}))}/><input placeholder="规范名称" value={form.canonical_name} onChange={e=>setForm(v=>({...v,canonical_name:e.target.value}))}/><input placeholder="简要说明" value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/><button className="primary compact" disabled={!form.canonical_name.trim()} onClick={()=>void create()}>创建</button><button className="secondary compact" onClick={()=>setCreating(false)}>取消</button></div>}
  <div className="knowledge-grid"><aside className="entity-index"><label><span className="sr-only">搜索实体</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索实体或说明…"/></label>{items.map(item=><button className={selectedID===item.id?"active":""} key={item.id} onClick={()=>setSelectedID(item.id)}><Network/><span><strong>{item.canonical_name}</strong><small>{item.type} · {item.aliases?.length??0} 个别名</small></span></button>)}{!items.length&&<p>还没有知识实体</p>}</aside>{selected?<EntityDetail workspace={workspace} entity={selected} entities={items} canEdit={canEdit} onReload={load}/>:<div className="collection-empty"><Network/><h2>选择一个实体</h2></div>}</div>
  <section className="mention-review"><header><div><h2>提及确认</h2><p>从最新内容版本中抽取的实体候选。</p></div><span>{mentions.length} 项待确认</span></header>{mentions.map(item=><article key={item.id}><button className="mention-content" onClick={()=>onOpenContent(item.content_id)}><strong>{item.content_title||"无标题"}</strong><small>{item.locale}</small></button><span>提及 <strong>{item.entity_name}</strong></span><small>{Math.round(item.confidence*100)}%</small>{canEdit&&<button className="secondary compact" onClick={()=>void api.confirmKnowledgeMention(workspace,item.id).then(load)}><Check/>确认</button>}</article>)}{!mentions.length&&<div className="collection-empty"><p>暂无待确认提及</p></div>}</section>
 </WorkspacePage>
}
